# Generated by Django 5.2.6 on 2025-09-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rename_transaction_id_payment_provider_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('mock', 'Mock')], default='mock', max_length=20),
        ),
    ]
